apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
  name: login
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 31100
    - name: apache
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31101
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 31102
  type: NodePort
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
    